import type { Abi, Address } from 'viem';
import deployments from './deployments.json';
import policyManagerAbiJson from './abis/PolicyManager.json';
import claimRegistryAbiJson from './abis/ClaimRegistry.json';
import payoutVaultAbiJson from './abis/PayoutVault.json';

const ZERO = '0x0000000000000000000000000000000000000000' as const;

/**
 * Env vars win over the checked-in deployment file, so a Vercel redeploy can
 * repoint at fresh contracts without a code change.
 */
function addressFrom(envValue: string | undefined, fallback: string): Address {
  const candidate = (envValue ?? fallback ?? ZERO).trim();
  return (/^0x[a-fA-F0-9]{40}$/.test(candidate) ? candidate : ZERO) as Address;
}

export const POLICY_MANAGER = addressFrom(
  process.env.NEXT_PUBLIC_POLICY_MANAGER,
  deployments.policyManager,
);
export const CLAIM_REGISTRY = addressFrom(
  process.env.NEXT_PUBLIC_CLAIM_REGISTRY,
  deployments.claimRegistry,
);
export const PAYOUT_VAULT = addressFrom(
  process.env.NEXT_PUBLIC_PAYOUT_VAULT,
  deployments.payoutVault,
);
export const USDC = addressFrom(process.env.NEXT_PUBLIC_USDC, deployments.usdc);

/** True once real contract addresses are configured; the UI explains itself when false. */
export const contractsConfigured =
  POLICY_MANAGER !== ZERO && CLAIM_REGISTRY !== ZERO;

// JSON imports widen every literal to `string`, which viem's `Abi` rejects.
// The files are generated by `forge build`, so the shape is trustworthy.
export const policyManagerAbi = policyManagerAbiJson as Abi;
export const claimRegistryAbi = claimRegistryAbiJson as Abi;
export const payoutVaultAbi = payoutVaultAbiJson as Abi;

export const erc20Abi = [
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'value', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const;

export const ETHERSCAN_BASE = 'https://sepolia.etherscan.io';

export function etherscanTx(hash: string): string {
  return `${ETHERSCAN_BASE}/tx/${hash}`;
}

export function etherscanAddress(address: string): string {
  return `${ETHERSCAN_BASE}/address/${address}`;
}
